language: c

sudo: false

matrix:
  include:
  - os: linux
    compiler: gcc
    env: O3=1
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - os: linux
    compiler: clang
    env: O3=1
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - os: linux
    compiler: gcc
    env: O3=1 STATIC=1
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - os: linux
    compiler: clang
    env: O3=1 STATIC=1
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - os: osx
    compiler: gcc
    env: O3=1
  - os: osx
    compiler: clang
    env: O3=1
  - os: osx
    compiler: gcc
    env: O3=1 STATIC=1
  - os: osx
    compiler: clang
    env: O3=1 STATIC=1

branches:
  only:
    - master

install:
  - ./autogen.sh
  - ./configure ${STATIC+--disable-shared} ${DEBUG+--enable-debug} ${VALGRIND+--enable-valgrind} ${CENSUS+--enable-census}
  - make V=1

script:
  - make check

after_failure:
  - for f in tests/*.log; do echo; echo "${f}:"; cat $f; done;
  - cat test-suite.log

notifications:
  email: false
